manifests/0000_09_machine-approver-04-deployment.yaml
specifies system-cluster-critical priority for deployment.
updates image pull policy to IfNotPresent
blocks passing smoke tests for ensuring control plane pods always schedule.
see: openshift/origin#22217
=> manifests: update priority and image pull policy

manifests/0000_09_machine-approver-00-ns.yaml
**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …
=> Add node-selector annotation to namespace

main.go
Some approval failures appear to be a result of machines temporarily
disappearing from the machine list. Retry failed approvals at least 5 times.
https://bugzilla.redhat.com/show_bug.cgi?id=1687295
@openshift/sig-auth
=> Bug 1687295: Retry failed approvals

manifests/04-deployment.yaml
In 4.1, we have taint-based evictions enabled. This changes logic in the node lifecycle controller in the kube-controller-manager significantly.
Historically, the node lifecycle controller would directly evict pods from node that had a Ready condition of False or Unknown after a pod eviction timeout set by the --pod-eviction-timeout flag on the kube-controller-manager. This setting applied to all pods cluster-wide. The default was 5m.
With taint-based evictions, all the node lifecycle controller does is taint the node with node.kubernetes.io/unreachable and/or node.kubernetes.io/not-ready taint with NoExecute effect. This would normally result in the immediate eviction of all pods that don't tolerate those taints, breaking the old behavior with pod eviction timeouts. Enter …
=> Fix tolerations

Makefile, config.go, csr_check.go, csr_check_test.go, main.go, manifests/02-clusterrole.yaml, manifests/04-deployment.yaml, node_client.go
Signed-off-by: Monis Khan <mkhan@redhat.com>
=> Handle node client certs

csr_check.go, csr_check_test.go
Increase machine creation time limit
GCP sometimes takes longer than 10 minutes to provision
a machine to the point of requesting a CSR.
Increase the limit slightly to allow more approvals.
Fixes: https://github.com/openshift/cluster-machine-approver/issues/36
=> Increase machine creation time limit

README.md
While working on integration of a new IPI platform type, I needed to
understand how automatic CSR approval worked, because it imposes some
expectations on each platform's cluster-api provider (or Machine
actuator).  This patch is adapted from some of my notes.
This expansion of the README aims to be a document that provides
background and pointers to important details for anyone looking
understand the CSR approval workflows.
=> README.md: Add cluster-machine-approver details.

main.go
The default exponential backoff is very low and sometimes a CSR will be
dropped from the queue betause the machine object did not have the
`nodeRef` added yet.
The current timeout is about 300 milliseconds. This should widen the
window. 10 retries result in about a 4 second window.
Fixes #40
=> Increase the CSR retry count to 30

manifests/04-deployment.yaml
Enables the CVO to exclude manifests in an externally hosted control plane deployment
See https://github.com/openshift/cluster-version-operator/pull/252
=> Add manifest annotations for hosted deployment exclusions

csr_check.go
This falls back to the original machine-api based checks for serving
certificate renewals if the checks based on retrieving the current
serving certificate fail.  This is needed in cases where network
interfaces are added to a machine after its initial creation, because
the SAN list in the new CSR will contain new addresses and no longer
match the current certificate exactly.
This requires the machine-controller to track all addresses on a
machine, which was recently fixed for AWS:
https://github.com/openshift/cluster-api-provider-aws/pull/277
=> Bug 1779107: Fall back to machine-api check if certificate check fails

csr_check.go, csr_check_test.go
Connections to IPv6 addresses were failing in `getServingCert` because
the address literal was not properly enclosed in square brackets.
This uses `net.JoinHostPort`, which handles this, in place of a simple
`fmt.Sprintf` call.
=> Fix IPv6 connections in getServingCert

manifests/04-deployment.yaml
For more detailed description see https://github.com/openshift/origin/issues/24247#issuecomment-560412327
=> Add resource request to container

manifests/0000_90_cluster-machine-approver_04_alertrules.yaml
Because the cluster machine approver is not deployed in a ROKS cluster, the alert that says that it's down should not be firing.
=> Bug 1809329: ROKS - remove ClusterMachineApproverDown prometheus rule

manifests/01-rbac.yaml
Successful TLS kubelet bootstrap for the [1.18 rebase](https://github.com/openshift/origin/pull/24719) requires that the approver have new rbac permissions as per [recent changes to the upstream approver](https://github.com/kubernetes/kubernetes/pull/88246).
=> Add RBAC signer rule for 1.18

status.go, status_test.go
We've used empty-string reasons since the status handling landed in ed1c8070d5 (#71).  But if we feel like we have a message we want to set to help humans understand the available condition, we should be setting a reason string for machines too.  `AsExpected` follows [the library-go precedent][1].
Also use `AsExpected` for some message-less but expected conditions, like `Progressing=False` and `Degraded=False`.  Having a reason makes it easier for folks skimming logs to see that the condition is in its happy state, and doesn't cost us any effort to set.
I am looking forward to the smarter logic promised by 91a58e6619 (#71), because the current blind assumption that everything is working seems... very optimistic ;).
[1]: https://github.com/openshift/library-go/blob/94c59dec54be25c8527e51e8c …
=> status: Add AsExpected reasons

README.md
The maximum difference between the machine creation timestamp and the
CSR creation timestamp has been increased to accomodate for baremetal
machines. The README still reported "10 minutes" instead of "2 hours".
ref.: https://github.com/openshift/cluster-machine-approver/pull/37
=> Document increased maxMachineDelta

manifests/0000_90_cluster-machine-approver_04_alertrules.yaml
The `general.rules` group name conflicts with others, causing them to be merged in OpenShift console via Thanos Querier.
This fixes it.
=> Bug 1866200: manifests: fix recording rules group name

Dockerfile.rhel, Dockerfile.rhel7
This creates a Dockerfile.rhel file according to convention and symlink Dockerfile.rhel7 to the new one to satisfy tooling consumers until we switch them
=> Bug 1872080: Create Dockerfile.rhel file

Dockerfile.rhel7
Since we consolidate on having Dockerfile.rhel named files in all repos and the build data is pointing to it https://github.com/openshift/ocp-build-data/pull/636 this can be dropped now
=> Bug 1875036: Remove deprecated Dockerfile.rhel7 file

manifests/04-deployment.yaml
Communicating with Kube API via localhost is discouraged because the caller doesn't know when the server is ready to serve the request. Reaching over the Kubernetes build-in service is preferred as it only contains the servers that are healthy and ready.
The following query shows that the operator frequently fails with errors like `127.0.0.1:6443: connect: connection refused` or `Failed to list *v1beta1.CertificateSigningRequest: certificatesigningrequests.certificates.k8s.io is forbidden: User "system:serviceaccount:openshift-cluster-machine-approver:machine-approver-sa" cannot list resource "certificatesigningrequests" in API group "certificates.k8s.io" at the cluster scope`
https://search.ci.openshift.org/?search=Failed+to+list+.*+is+forbidden%3A+.*+in+API+group&maxAge=48h&context=1&typ …
=> Bug 1879159: stop communicating with Kube API via localhost

manifests/00-ns.yaml, manifests/0000_90_cluster-machine-approver_01_prometheusrole.yaml, manifests/0000_90_cluster-machine-approver_02_prometheusrolebinding.yaml, manifests/0000_90_cluster-machine-approver_03_servicemonitor.yaml, manifests/0000_90_cluster-machine-approver_04_alertrules.yaml, manifests/01-rbac.yaml, manifests/02-kube-rbac-proxy-config.yaml, manifests/03-metrics-service.yaml, manifests/04-deployment.yaml, manifests/05-clusteroperator.yaml
This is matches openshift/enhancements#414 and doesn't change existing behavior
=> add current profile annotations to CVO manifests

manifests/04-deployment.yaml
The Kube RBAC Proxy containers are logging excessively. Having log level 10 includes logging bearer tokens and full http request/responses. This is insecure, more logging than we need, and has an impact on aggregated logging. Reduce to 3 to be inline with other components.
=> Bug 1907380: Reduce verbosity of kube-rbac-proxy logging

manifests/04-deployment.yaml
The default ciphers are not secure and are susceptible to a number of different known vulnerabilities. This collection of ciphers should be more secure and have no known vulnerabilities present.
Suites inspired by the [cluster-monitoring-operator](https://github.com/openshift/cluster-monitoring-operator/blob/f98cd6d7d1dc50fe881c6aa29d772a581451afd1/manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml#L54).
=> Bug 1923823: Improve TLS configuration for Kube RBAC Proxy

pkg/controller/controller.go, pkg/controller/csr_check.go, pkg/controller/csr_check_test.go
Currently, logging is almost nonexistent.  Returning
errors to the controller manager does not result in viewable
messages on current verbosity.  This commit adds explicit
klog statements for better debugging and tracability.
Currently, we return error to the controller manager too often.  This
results in CSRs being endlessly requeued which will never be approved.
This commit less-eagerly requeues CSRs for most permanent failure modes.
=> Refactor logging and error handling

Makefile, hack/go-mod.sh, hack/goimports.sh, hack/imagebuilder.sh
Enable running make targets inside container with either `podman` or `docker`, podman being the default choice if installed, or outside container when `NO_DOCKER=1` specified.
=> Enable running make targets inside container

go.sum, pkg/controller/controller.go, pkg/controller/csr_check.go, pkg/controller/csr_check_test.go, pkg/controller/node_client.go
Move certificates to v1 because v1beta1 will be removed in 4.9.
=> Bug 1947785: Move certificates to v1

Dockerfile, Dockerfile.rhel
This PR bumps the image and golang version to 1.16
=> Bug 1949741: bump golang versions

pkg/controller/csr_check.go, pkg/controller/csr_check_test.go
This commit ensures serving certs are requeued in case the node link
controller has not yet updated the machine object.
=> Bug 1952282: Ensure serving certs requeued

manifests/00-ns.yaml, manifests/04-deployment.yaml
In support of the workload partitioning feature
(openshift/enhancements#703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
=> Add management workload annotations

main.go
We have observed that reading stale data for Machine and Node objects from the cache can cause node bootstrap failures as the approver does not recognise the correct links between CSRs, Machines and Nodes. To prevent reading stale data, only allow the client to return Machine and Node objetcs and lists directly from the API server instead of from the informer cache.
=> Bug 1956609: Bypass cache when reading Node and Machine objects

main.go
`mgr.GetClient()` returns a cached client that reads from the informers within the controller. We need to use an uncached client for the `Client` in the delegating client to make sure that non cached reads hit the API server directly.
=> Bug 1956609: Use a direct client for uncached reads

manifests/0000_90_cluster-machine-approver_04_alertrules.yaml
The alert was added in 2e7f847b29 (#50).  But the cluster-version operator is responsible for complaining if the machine approver operator's deployment is sad, so no need for the operator to handle this directly (we end up doubling up if there's an issue).
Similar to openshift/cloud-credential-operator#308, openshift/cluster-autoscaler-operator#196, and openshift/machine-api-operator#826.
=> manifests/0000_90_cluster-machine-approver_04_alertrules: Drop ClusterMachineApproverDown

manifests/05-clusteroperator.yaml
To ensure that must-gather can run correctly when CMA has not started properly, we can prepopulate the relatedObjects field. CVO will pre-create this resource and must-gather will know which resources to pull even if CMA never set these itself
=> [OCPCLOUD-1175] Ensure must-gather tracks related objects on failures

go.mod, go.sum, main.go, pkg/controller/controller.go, pkg/controller/csr_check.go, pkg/controller/csr_check_test.go, pkg/machinehandler/machinehandler.go, vendor/github.com/mitchellh/mapstructure/.travis.yml, vendor/github.com/mitchellh/mapstructure/CHANGELOG.md, vendor/github.com/mitchellh/mapstructure/LICENSE, vendor/github.com/mitchellh/mapstructure/README.md, vendor/github.com/mitchellh/mapstructure/decode_hooks.go, vendor/github.com/mitchellh/mapstructure/error.go, vendor/github.com/mitchellh/mapstructure/go.mod, vendor/github.com/mitchellh/mapstructure/mapstructure.go, vendor/modules.txt
In order to make cluster machine approver work with CAPI and MAPI machines, I converted the code to use unstructured. The API group is passed as a CLI argument and defaults to MAPI. The unstructured approach is similar to what is done in autoscaler.
=> Add support for unstructured machines

pkg/controller/controller.go
This is a manual cherry pick of #135
> Currently, we reconcile the limits (which the metrics are sourced from) at the beginning of the reconcile loop.
> 
> We only reconcile when there is a pending CSR.
> 
> So at the beginning of the reconcile loop, there is 1 pending CSR, we set the metric to 1.
> We then approve the CSR, now there are no pending CSRs, so we don't have anything to reconcile.
> With no reconciles happening, we never update the metric value, so it stays at 1.
>
> This PR adjusts so that once we have reconciled, assuming it was successful, we re-reconcile the limits (metrics) to ensure they are still up to date. If we made an approval during the reconcileCSR this should now be accounted for
during the metric collection.
>
> If there are any errors throughout this, we don't …
=> Bug 2019754: Ensure pending CSR count is valid post approval

main.go, manifests/01-rbac.yaml, pkg/controller/csr_check.go, pkg/controller/csr_check_test.go
Manual cherry-pick of #137. 
> When using the OpenShift Egress IP feature (only available on select platforms, eg vSphere), with SDN, additional IPs are assigned to the network interfaces for the VM. These are then picked up by kubelet and added to the CSR SANs.
>
>In IPI clusters, these IPs are also picked up by Machine API and the IP addresses are listed in the Machine status. During certificate renewals, these IPs are matched and the CSR is approved.
>
>When using IPI clusters, we expect the SANs to match. Because Egress IPs come and go, this isn't reliably the case. To allow this use case, this PR adjusts the CMA so that if the CSRs don't match exactly, because of the IP address list being different, the check will allow the CSR to contain any previously allowed IPs plus any IPs that …
=> Bug 2024216: Allow fallback to serving cert renewal accounting for egress IPs on SDN

manifests/0000_90_cluster-machine-approver_04_alertrules.yaml
this brings the alerts into compliance with the style guide for
openshift.
ref:
https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#style-guide
=> Bug 2010359: add summary and description to alerts

main.go, manifests/01-rbac.yaml, pkg/controller/csr_check.go, pkg/controller/csr_check_test.go
Manual cherry-pick of #137
> When using the OpenShift Egress IP feature (only available on select platforms, eg vSphere), with SDN, additional IPs are assigned to the network interfaces for the VM. These are then picked up by kubelet and added to the CSR SANs.
>
>In IPI clusters, these IPs are also picked up by Machine API and the IP addresses are listed in the Machine status. During certificate renewals, these IPs are matched and the CSR is approved.
>
>When using IPI clusters, we expect the SANs to match. Because Egress IPs come and go, this isn't reliably the case. To allow this use case, this PR adjusts the CMA so that if the CSRs don't match exactly, because of the IP address list being different, the check will allow the CSR to contain any previously allowed IPs plus any IPs that …
=> Bug 2024689: Allow fallback to serving cert renewal accounting for egress IPs on SDN

OWNERS
This PR removes old team members and adds new ones.
=> OWNERS: remove old team members, add new ones

pkg/controller/controller.go, pkg/controller/csr_check_test.go
If more than 100 machines need to renew their certificates at once on a UPI cluster today, we exhaust the capacity limit set by the maxPending check. To allow renewal in these cases we need to account for how many Nodes have joined the cluster before we block the approvals
=> Bug 2028019: Account for large scale simultaneous renewal on UPI clusters

README.md
This came up in the context of https://github.com/redhat-et/microshift
Let's cross-reference to the MCO and specifically the MCS code
which handles the token, since it's important to understand
specifically for OpenShift.
=> README.md: Elaborate a bit more on node join

pkg/controller/csr_check_test.go
x509.CreateCertificate function casts validity time to utc under the hood
https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/crypto/x509/x509.go;l=1538
=> Make 'reject_expired' tests works in any time zone

pkg/controller/csr_check_test.go
This pr contains:
- Moving machines creation to function in Test_authorizeCSR test suite.
- CRs generation was moved to function, instead of having constants in test file.
For ensure that generated CRs attrs are equal to constant ones this [commit](https://github.com/openshift/cluster-machine-approver/pull/155/commits/eaec2db32f83d6812a2d09cdf5bca98352473b5e) contained test. 
Run results might be checked here: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-machine-approver/155/pull-ci-openshift-cluster-machine-approver-master-unit/1488863004706476032/build-log.txt
=> Shrink csr_check_test.go size

go.mod, main.go, manifests/04-deployment.yaml, pkg/controller/controller.go, pkg/machinehandler/machinehandler.go, pkg/machinehandler/machinehandler_test.go
Currently approver can work with just one API group, which is defined by --apigroup option. This patch allows to set several API groups, so that the component is able to approve certificates for machines created by various APIs.
For OpenShift it means that we don't have to deploy 2 approvers: one for MAPI and another for CAPI. Instead we can use one instance that manages them all.
Also, using of api-group-version instead of just api-group allows us to define what API version we'd like to use. It's important because In openshift/machine-api-operator#992, we are introducing a new CRD which is in the machine.openshift.io/v1 group. This means that the server preferred version of the API is now v1 and not v1beta1. Because Machines don't yet exist in the v1 group, this means the CMA is …
=> Allow to define several API groups

manifests/01-rbac-capi.yaml, manifests/04-deployment-capi.yaml
Add techpreview manifests for CAPI machines, this is the easiest way to have CMA work with CAPI machines in techpreview phase.
=> Add techpreview manifests for CAPI machines

manifests/04-deployment.yaml
This allows the command `oc -n openshift-cluster-machine-approver logs deploy/machine-approver` to run and grab the `machine-approver-controller` logs by default (the `kube-rbac-proxy` container logs are usually less interesting)
=> Set default container for log retrieval

pkg/controller/csr_check.go
Related to OSD-12989.  The machine approver doesn't recognize hostnames that use capital letters as valid even though DNS is case-insensitive.  This change will allow the machine approver to properly recognize those hostnames.
=> ignore case when checking csr hostnames

manifests/01-rbac-capi.yaml, manifests/04-deployment-capi.yaml
This was added in https://github.com/openshift/cluster-version-operator/pull/821 to allow more featuresets and allow for a future migration to include actual gates. Because usage of this manifest would prevent upgrades, there are not upgrade concerns for this change.
=> update to release.openshift.io/feature-set to match OCP 4.12

manifests/04-deployment-capi.yaml
In case of single node installations two CMA deployments tries to use same set of ports for metrics.
Set another ports for CAPI related CMA deployment.
=> OCPBUGS-2621: Update capi related CMA deployment ports

pkg/controller/node_client.go
We missed the client cert path in https://github.com/openshift/cluster-machine-approver/pull/184.
=> OCPBUGS-11225: Update isNodeClientCert to allow for new key usages

main.go, pkg/controller/csr_check_test.go
We were getting error messages from controller-runtime that no logger is set for it. This patch fixes that.
=> OCPBUGS-17090: Set logger for controller runtime

pkg/controller/controller.go, pkg/controller/csr_check.go, pkg/controller/csr_check_test.go, pkg/metrics/metrics.go
CSRs not created by node bootstrapper are correctly filtered out in the reconciler, but this filtering was not performed when reporting metrics. 
This PR adds the necessary filtering and clarifies what the metrics report.
=> OCPBUGS-21594: Filter non node CSRs in metrics

manifests/04-deployment.yaml, pkg/metrics/metrics.go
This is a draft PR to spin up a cluster to test my changes for [OCPCLOUD-2277](https://issues.redhat.com//browse/OCPCLOUD-2277) - will create a more useful description once I can confirm this change works as expected.
=> OCPCLOUD-2277: Ensure Cluster Machine Approver metrics are only available via HTTPS

Makefile, pkg/controller/controller.go, pkg/controller/csr_check.go, pkg/controller/csr_check_test.go, pkg/metrics/metrics.go
Cherry-pick of https://github.com/openshift/cluster-machine-approver/pull/210 with `NO_DOCKER=1` cherry-pick.
=>  [release-4.12] OCPBUGS-23486: Filter non node CSRs in metrics

main.go, manifests/04-deployment-capi.yaml, manifests/04-deployment.yaml, pkg/controller/csr_check.go, pkg/controller/csr_check_test.go
Approving CSRs should not need to be in sequence, we should be able to process in parallel. Kubelet will create CSRs when it starts and these should be approved in a timely manner. On large scale events, we are slow to process the CSRs and this is causing kubelet to create duplicate CSRs.
Creating duplicates leads to us exhausting our limit which stops approval altogether.
The only time where we may have an issue is if 2 concurrent reconciles approve client CSRs for the same node at the same time, this today has a check in place such that we don't approve client CSRs when nodes already exist. In theory, this should never happen if we are approving the client CSRs promptly anyway.
I also noticed while working on this, that we are accounting for Multus CSRs when calculating the pending …
=> OCPBUGS-23544: Increase concurrent reconciles to 10

manifests/04-deployment.yaml
All openshift operators must include FallbackToLogsOnError to ease debugging.
=> OCPBUGS-28230: add FallbackToLogsOnError for easier debugging

pkg/controller/csr_check_test.go, pkg/machinehandler/machinehandler.go
DNS names are case insensitive. Kubelet automatically lower cases names, but, our actuators may not (especially on AWS). In this case, the client certificates cannot be approved, because we currently look for an exact match between the node name and the DNS name.
=> OCPBUGS-36871: Client internal DNS checks should be case insensitive

pkg/controller/csr_check_test.go, pkg/machinehandler/machinehandler.go
Users may desire to configure their AWS DHCP Option Set with a custom domain name, that contains a trailing dot, but a trailing dot is not permitted in a Kubernetes object name per the DNS 1123 subdomain name standard, so met the bug [OCPBUGS-45306](https://issues.redhat.com/browse/OCPBUGS-45306). We fixed that in the pr https://github.com/openshift/machine-config-operator/pull/4729 to ensure that we trim any trailing dot prior to passing the hostname over to kubelet. 
But a new issue is the client certificates cannot be approved, because we currently look for an exact match (only ignore case) between the node name and the DNS name, and in this case the node name without the trailing dot, but the DNS name with the trailing dot. So update it to ignore the trailing dot when matching.
=> OCPBUGS-45306: Client internal DNS checks should ignore trailing dot

pkg/controller/csr_check.go, pkg/controller/csr_check_test.go
This is a follow up to https://github.com/openshift/cluster-machine-approver/pull/248, which fixed the issue for client certificates. However, we also need to fix this for serving certificates so that we can access things like logs or oc debug on the node.
=> OCPBUGS-45306: Ensure trailing dots on DNS names do not block serving cert auth

main.go, pkg/controller/controller.go, pkg/controller/csr_check.go, pkg/controller/csr_check_test.go
Updates to CSR filtering to utilize signerName field using the well known certificatesv1.KubeAPIServerClientKubeletSignerName and certificatesv1.KubeletServingSignerName.
Also updates the CSR query to use node selectors with signerName to be more efficient on cluster with many irrelevant CSRs
=> OCPBUGS-36404: Filter CSRs by signerName

manifests/01-rbac-capi.yaml, manifests/04-deployment-capi.yaml
We need these manfiests deployed in CustomNoUpgrade as we begin work & testing on the MAPI2CAPI Migration controllers. This will enable e2es to run.
=> OCPCLOUD-2787: Deploy CAPI manifests in CustomNoUpgrade

.snyk
Checking if ignoring the test file , will remove snyk failure .
=> No-Jira: ignore test file csr_check_test.go

manifests/04-deployment-capi.yaml, manifests/04-deployment.yaml
- As we use `kubectl logs -n openshift-cluster-machine-approver machine-approver-xxxx`, we see the default container logs is `kube-rbac-proxy`, like :
```
Defaulted container "kube-rbac-proxy" out of: kube-rbac-proxy, machine-approver-controller
I0910 05:51:38.746320       1 flags.go:64] FLAG: --add-dir-header="false"
I0910 05:51:38.746472       1 flags.go:64] FLAG: --allow-paths="[]"
I0910 05:51:38.746479       1 flags.go:64] FLAG: --alsologtostderr="false"
I0910 05:51:38.746481       1 flags.go:64] FLAG: --auth-header-fields-enabled="false"
I0910 05:51:38.746483       1 flags.go:64] FLAG: --auth-header-groups-field-name="x-remote-groups"
I0910 05:51:38.746487       1 flags.go:64] FLAG: --auth-header-groups-field-separator="|"
I0910 05:51:38.746489       1 flags.go:64] FLAG: …
```
=> NO-JIRA: set machine-approver-controller as default container
