csr_check.go, main.go
My worker's CSRs aren't being approved and this would help me
debug why.
=> Add CSR failure cause to logs

main.go
@openshift/sig-auth 
https://bugzilla.redhat.com/show_bug.cgi?id=1702098
=> Bug 1702098: Do not mutate cached CSR

Dockerfile, Dockerfile.rhel7
=> Fix typo in dockerfiles

config.go, main.go
A mix of klog and glog was being used, and klog was not properly initialized. This is making problems impossible to debug.
=> Properly initialize klog and fix logging

csr_check.go, csr_check_test.go
Add consumer given values to logs
=> Add consumer given values to logs

csr_check_test.go, main.go
Re open https://github.com/openshift/cluster-machine-approver/pull/33 squashed in one commit
=> Increase pending allowed

csr_check.go, csr_check_test.go
Add more logging for failed isReqFromNodeBootstrapper
=> Add more logging for failed isReqFromNodeBootstrapper

csr_check.go, csr_check_test.go
This relaxes the constraints on comparison of Subject Alternative Name
values in CSRs for serving cert renewals.  It doesn't take into
account ordering, and checks only the string representation of IP
addresses and URLs.
=> Relax SAN comparison constraints

Makefile, hack/e2e.sh
Add machine api e2e script to be run by CI
=> Add machine api e2e script to be run by CI

manifests/04-deployment.yaml
This sneaked in here https://github.com/openshift/cluster-machine-approver/pull/50
=> Remove host port exposed in the proxy container

csr_check.go, csr_check_test.go
This falls back to the original machine-api based checks for serving
certificate renewals if the checks based on retrieving the current
serving certificate fail. This is needed in cases where network
interfaces are added to a machine after its initial creation, because
the SAN list in the new CSR will contain new addresses and no longer
match the current certificate exactly.
This requires the machine-controller to track all addresses on a
machine, which was recently fixed for AWS: https://github.com/openshift/cluster-api-provider-aws/pull/279
Cherry-picks for other relases:
https://github.com/openshift/cluster-machine-approver/pull/57
https://github.com/openshift/cluster-machine-approver/pull/58
This also cherry-picks: https://github.com/openshift/cluster-machine-approver/pull/51
=> [release-4.2] Bug 1781160: Fall back to machine-api check if certificate check fails

OWNERS
Update OWNERS with current team members
=> Update OWNERS with current team members

docs/dev/metrics.md
This change brings in a new document that describes the available
metrics.
=> add a metrics document

manifests/00-ns.yaml, manifests/0000_90_cluster-machine-approver_01_prometheusrole.yaml, manifests/0000_90_cluster-machine-approver_02_prometheusrolebinding.yaml, manifests/0000_90_cluster-machine-approver_03_servicemonitor.yaml, manifests/0000_90_cluster-machine-approver_04_alertrules.yaml, manifests/01-rbac.yaml, manifests/02-kube-rbac-proxy-config.yaml, manifests/03-metrics-service.yaml, manifests/04-deployment.yaml, manifests/05-clusteroperator.yaml
This implements phase 1 of openshift/enhancements#482
=> Annotate manifests for single-node-developer cluster profile

csr_check.go, csr_check_test.go
Porting introduced testst from https://github.com/openshift/cluster-machine-approver/pull/73/commits/a7a33f99fe82374879b54d9fa558628fd9e9ff5d as a part of https://github.com/openshift/cluster-machine-approver/pull/73, which are adding full coverage of `csr_check.go` package.
```
Before
ok  	github.com/openshift/cluster-machine-approver	7.143s	coverage: 46.7% of statements
After
ok  	github.com/openshift/cluster-machine-approver	(cached)	coverage: 63.7% of statements
```
Depends on https://github.com/openshift/cluster-machine-approver/pull/96
=> [OCPCLOUD-1042] Increase test coverage in CSR approval

manifests/00-ns.yaml, manifests/0000_90_cluster-machine-approver_01_prometheusrole.yaml, manifests/0000_90_cluster-machine-approver_02_prometheusrolebinding.yaml, manifests/0000_90_cluster-machine-approver_03_servicemonitor.yaml, manifests/01-rbac.yaml, manifests/02-kube-rbac-proxy-config.yaml, manifests/03-metrics-service.yaml
This matches https://github.com/openshift/enhancements/pull/445 and does
not change behavior.
=> Add IBM Cloud managed annotations to CVO manifests

main.go
Mitigate potential for stale cache and cover edge case for https://bugzilla.redhat.com/show_bug.cgi?id=1940972
This is not a fix for the bug according to discussion on bugzilla, but before the controller-runtime issue is investigated might as well be.
=> Bug 1940972: Increase cache resync period to 10 min instead of 10 hours

pkg/controller/controller.go
When adding a CSR to the queue, we filter based on whether the CSR is already approved. We don't however check this again during the reconciliation loop.
In certain scenarios, we can end up in a situation where the CSR is approved externally before we get to it. In this case, the approval call for to the API server fails as we are duplicating the approved condition. When this API call fails, this causes the CSR to requeue and we end up with the CSR in a constant loop of attempting to be approved, but unable for it to actually be approved.
To prevent this, before we reconcile any CSR, we should check that it hasn't already been approved out of band.
=> Bug 2003788: Prevent error loop when a CSR is queued and then approved externally

main.go, pkg/controller/controller.go, pkg/machinehandler/machinehandler.go, pkg/machinehandler/machinehandler_test.go
Updates:
- Added `--machine-namespace` as a new argument to list machine in a namespace. 
If not given, will list machines in cluster scope. (same as before)
=> add machine-namespace

pkg/controller/controller.go
This change updates the approval condition logic to detect when the
condition already exists in the CSR record. If the condition already
exists, and has a different state than is desired, the condition will be
updated. If the condition does not exist, it will be created and added
to the CSR record.
When the condition does not need to be updated, the approve logic will
now skip sending an update to the API server.
=> Bug 1978303: update approve condition logic

pkg/controller/controller.go, pkg/controller/csr_check.go
Fixes mapi_current_pending_csr metric being stuck at 1
after CSR is rejected by CMA and subsequently approved by another
controller
Not sure if using condition message in logic is bad, but storing approving controller in there avoids running redundant reconciles.
Why the bug occurs:
There are two types of CSRs, client CSR and server CSR. CMA handles both for initial approval. But only the server certificate during renewal. What happens is we get client CSR to reconcile, recognize that it is not for us to approve and leave it pending. Increasing mapi_current_pending_csr metric.
After that kube-controller-manager approves the CSR but we ignore the certificate because it is already approved leaving the metric unchanged.
How this PR fixes the issue:
We run reconcile on CSRs if they have been …
=> Bug 2047702: Reconcile CSRs approved by other controllers

pkg/controller/controller.go, pkg/controller/csr_check.go
This is a backport of https://github.com/openshift/cluster-machine-approver/pull/160 to 4.10.
=> Bug 2072928: Reconcile recently approved CSRs by other controllers

README.md
Signed-off-by: T K Chandra Hasan <t.k.chandra.hasan@ibm.com>
=> Update TLS Bootstrapping doc links in README

pkg/controller/csr_check.go, pkg/controller/csr_check_test.go
Relax the validation usages needed for ECDSA CSRs.
ref: https://github.com/kubernetes/kubernetes/pull/111660
=> OCPBUGS-11225: approver: fix ECDSA approvals in 1.27

pkg/machinehandler/machinehandler.go
We try to check if MAPI is present
in the cluster before trying to
query them. This is needed in order
to make MAPI optional.
=> OCPBUGS-16156: check if machine api present

.snyk
Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!
=> OCPBUGS-26116: Add Snyk file to exclude vendor directory on scan

pkg/machinehandler/machinehandler.go, pkg/machinehandler/machinehandler_test.go
Avoid fetching machines from api when machines api is not present in the cluster
=> OCPBUGS-33644: check for machine crd before listing machines

status_test.go
The status controller creates a ClusterOperator when one does not exist. In the test case verifying behavior with an already present ClusterOperator, it is requried to wait until the ClusterOperator created by the test is ready. Failing to do so can result in the controller attempting to create a duplicate ClusterOperator, causing the test to fail with an "already exists" error.
This PR adds waitgroup to ensure we start the controller after existingCO is created.
=> OCPBUGS-48056: Fix race condition in CO status controller test

pkg/controller/csr_check.go
=> OCPBUGS-19856: Improve log message when searching for node by InternalDNS

pkg/controller/csr_check.go, pkg/controller/csr_check_test.go
- **Remove dead code**
- **Fix incorrect usage of break**
- **errors should not be capitalised**
=> NO-JIRA: Fix some lints and nits
